name: chess_mobile_game
description: Chess Mobile Game
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.8
  firebase_storage: ^11.5.5
  flutter_svg: ^2.0.9
  go_router: ^12.1.3
  intl: ^0.19.0
  provider: ^6.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
